"""
Use try/except to catch an error, you can try to validate
what happens when we do

int("Hello")
"""


"""
Cause an exception to be raised using the raise function and
print a message after you have finished catching the error
at finally.
"""


"""
Use input function to request information to the user and in
the try/except structure catches multiple errors that can be
generated
"""
